### ISSUE TITLE
Add an this.insertView (or equivalent) for dynamic subviews.

### ISSUE THREAD

**Issue by abritinthebay** [justspamjustin/BossView#3]
Right now I'm reduced to the following for dynamic updating

```
_.each(dynamicListOfViews, function (itemData, name) {
    this.options.subViews[name] = function () {
        var model = new MyModel(itemData);
        return new MyView({model: model});
    };
}, this);
this._initializeSubViews();
this._initializeChildViewEvents();
this._initializeSubViewEventBubbling();
```

This is obviously a bit rough. 

A simple insertView/addSubView method could takethe view (or object for a list of views) and then do the needed setup.

Would create much cleaner code when dealing with dynamic subviews (that may not be directly from a collection for example).

Sure I could make a contrived collection and use some form of CollectionView but then I end up writing a whole lot of other boilerplate code that doesn't really solve the issue _and_ I end up not at an ideal solution anyhow :(

**Comment by agwidarsito** [comment]
Haha, great work for this :-)
